// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket.proto

package via.sep3.grpcserver.protobuf.ticketservices;

/**
 * Protobuf type {@code SeatTicketResponse}
 */
public final class SeatTicketResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SeatTicketResponse)
    SeatTicketResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SeatTicketResponse.newBuilder() to construct.
  private SeatTicketResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SeatTicketResponse() {
    passengerId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SeatTicketResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SeatTicketResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 17: {

            seatPrice_ = input.readDouble();
            break;
          }
          case 24: {

            totalSeats_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            passengerId_ = s;
            break;
          }
          case 40: {

            tripId_ = input.readInt64();
            break;
          }
          case 50: {
            via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder subBuilder = null;
            if (pickup_ != null) {
              subBuilder = pickup_.toBuilder();
            }
            pickup_ = input.readMessage(via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pickup_);
              pickup_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder subBuilder = null;
            if (dropoff_ != null) {
              subBuilder = dropoff_.toBuilder();
            }
            dropoff_ = input.readMessage(via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dropoff_);
              dropoff_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.grpcserver.protobuf.ticketservices.Ticket.internal_static_SeatTicketResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.grpcserver.protobuf.ticketservices.Ticket.internal_static_SeatTicketResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse.class, via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int SEAT_PRICE_FIELD_NUMBER = 2;
  private double seatPrice_;
  /**
   * <code>double seat_price = 2;</code>
   * @return The seatPrice.
   */
  @java.lang.Override
  public double getSeatPrice() {
    return seatPrice_;
  }

  public static final int TOTAL_SEATS_FIELD_NUMBER = 3;
  private int totalSeats_;
  /**
   * <code>int32 total_seats = 3;</code>
   * @return The totalSeats.
   */
  @java.lang.Override
  public int getTotalSeats() {
    return totalSeats_;
  }

  public static final int PASSENGER_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object passengerId_;
  /**
   * <code>string passenger_id = 4;</code>
   * @return The passengerId.
   */
  @java.lang.Override
  public java.lang.String getPassengerId() {
    java.lang.Object ref = passengerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      passengerId_ = s;
      return s;
    }
  }
  /**
   * <code>string passenger_id = 4;</code>
   * @return The bytes for passengerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPassengerIdBytes() {
    java.lang.Object ref = passengerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      passengerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRIP_ID_FIELD_NUMBER = 5;
  private long tripId_;
  /**
   * <code>int64 trip_id = 5;</code>
   * @return The tripId.
   */
  @java.lang.Override
  public long getTripId() {
    return tripId_;
  }

  public static final int PICKUP_FIELD_NUMBER = 6;
  private via.sep3.grpcserver.protobuf.ticketservices.LocationMessage pickup_;
  /**
   * <code>.LocationMessage pickup = 6;</code>
   * @return Whether the pickup field is set.
   */
  @java.lang.Override
  public boolean hasPickup() {
    return pickup_ != null;
  }
  /**
   * <code>.LocationMessage pickup = 6;</code>
   * @return The pickup.
   */
  @java.lang.Override
  public via.sep3.grpcserver.protobuf.ticketservices.LocationMessage getPickup() {
    return pickup_ == null ? via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.getDefaultInstance() : pickup_;
  }
  /**
   * <code>.LocationMessage pickup = 6;</code>
   */
  @java.lang.Override
  public via.sep3.grpcserver.protobuf.ticketservices.LocationMessageOrBuilder getPickupOrBuilder() {
    return getPickup();
  }

  public static final int DROPOFF_FIELD_NUMBER = 7;
  private via.sep3.grpcserver.protobuf.ticketservices.LocationMessage dropoff_;
  /**
   * <code>.LocationMessage dropoff = 7;</code>
   * @return Whether the dropoff field is set.
   */
  @java.lang.Override
  public boolean hasDropoff() {
    return dropoff_ != null;
  }
  /**
   * <code>.LocationMessage dropoff = 7;</code>
   * @return The dropoff.
   */
  @java.lang.Override
  public via.sep3.grpcserver.protobuf.ticketservices.LocationMessage getDropoff() {
    return dropoff_ == null ? via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.getDefaultInstance() : dropoff_;
  }
  /**
   * <code>.LocationMessage dropoff = 7;</code>
   */
  @java.lang.Override
  public via.sep3.grpcserver.protobuf.ticketservices.LocationMessageOrBuilder getDropoffOrBuilder() {
    return getDropoff();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (java.lang.Double.doubleToRawLongBits(seatPrice_) != 0) {
      output.writeDouble(2, seatPrice_);
    }
    if (totalSeats_ != 0) {
      output.writeInt32(3, totalSeats_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(passengerId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, passengerId_);
    }
    if (tripId_ != 0L) {
      output.writeInt64(5, tripId_);
    }
    if (pickup_ != null) {
      output.writeMessage(6, getPickup());
    }
    if (dropoff_ != null) {
      output.writeMessage(7, getDropoff());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (java.lang.Double.doubleToRawLongBits(seatPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, seatPrice_);
    }
    if (totalSeats_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalSeats_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(passengerId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, passengerId_);
    }
    if (tripId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, tripId_);
    }
    if (pickup_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getPickup());
    }
    if (dropoff_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDropoff());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse)) {
      return super.equals(obj);
    }
    via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse other = (via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse) obj;

    if (getId()
        != other.getId()) return false;
    if (java.lang.Double.doubleToLongBits(getSeatPrice())
        != java.lang.Double.doubleToLongBits(
            other.getSeatPrice())) return false;
    if (getTotalSeats()
        != other.getTotalSeats()) return false;
    if (!getPassengerId()
        .equals(other.getPassengerId())) return false;
    if (getTripId()
        != other.getTripId()) return false;
    if (hasPickup() != other.hasPickup()) return false;
    if (hasPickup()) {
      if (!getPickup()
          .equals(other.getPickup())) return false;
    }
    if (hasDropoff() != other.hasDropoff()) return false;
    if (hasDropoff()) {
      if (!getDropoff()
          .equals(other.getDropoff())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + SEAT_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSeatPrice()));
    hash = (37 * hash) + TOTAL_SEATS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSeats();
    hash = (37 * hash) + PASSENGER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPassengerId().hashCode();
    hash = (37 * hash) + TRIP_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTripId());
    if (hasPickup()) {
      hash = (37 * hash) + PICKUP_FIELD_NUMBER;
      hash = (53 * hash) + getPickup().hashCode();
    }
    if (hasDropoff()) {
      hash = (37 * hash) + DROPOFF_FIELD_NUMBER;
      hash = (53 * hash) + getDropoff().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SeatTicketResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SeatTicketResponse)
      via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.grpcserver.protobuf.ticketservices.Ticket.internal_static_SeatTicketResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.grpcserver.protobuf.ticketservices.Ticket.internal_static_SeatTicketResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse.class, via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse.Builder.class);
    }

    // Construct using via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      seatPrice_ = 0D;

      totalSeats_ = 0;

      passengerId_ = "";

      tripId_ = 0L;

      if (pickupBuilder_ == null) {
        pickup_ = null;
      } else {
        pickup_ = null;
        pickupBuilder_ = null;
      }
      if (dropoffBuilder_ == null) {
        dropoff_ = null;
      } else {
        dropoff_ = null;
        dropoffBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.grpcserver.protobuf.ticketservices.Ticket.internal_static_SeatTicketResponse_descriptor;
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse getDefaultInstanceForType() {
      return via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse build() {
      via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse buildPartial() {
      via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse result = new via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse(this);
      result.id_ = id_;
      result.seatPrice_ = seatPrice_;
      result.totalSeats_ = totalSeats_;
      result.passengerId_ = passengerId_;
      result.tripId_ = tripId_;
      if (pickupBuilder_ == null) {
        result.pickup_ = pickup_;
      } else {
        result.pickup_ = pickupBuilder_.build();
      }
      if (dropoffBuilder_ == null) {
        result.dropoff_ = dropoff_;
      } else {
        result.dropoff_ = dropoffBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse) {
        return mergeFrom((via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse other) {
      if (other == via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getSeatPrice() != 0D) {
        setSeatPrice(other.getSeatPrice());
      }
      if (other.getTotalSeats() != 0) {
        setTotalSeats(other.getTotalSeats());
      }
      if (!other.getPassengerId().isEmpty()) {
        passengerId_ = other.passengerId_;
        onChanged();
      }
      if (other.getTripId() != 0L) {
        setTripId(other.getTripId());
      }
      if (other.hasPickup()) {
        mergePickup(other.getPickup());
      }
      if (other.hasDropoff()) {
        mergeDropoff(other.getDropoff());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private double seatPrice_ ;
    /**
     * <code>double seat_price = 2;</code>
     * @return The seatPrice.
     */
    @java.lang.Override
    public double getSeatPrice() {
      return seatPrice_;
    }
    /**
     * <code>double seat_price = 2;</code>
     * @param value The seatPrice to set.
     * @return This builder for chaining.
     */
    public Builder setSeatPrice(double value) {
      
      seatPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double seat_price = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeatPrice() {
      
      seatPrice_ = 0D;
      onChanged();
      return this;
    }

    private int totalSeats_ ;
    /**
     * <code>int32 total_seats = 3;</code>
     * @return The totalSeats.
     */
    @java.lang.Override
    public int getTotalSeats() {
      return totalSeats_;
    }
    /**
     * <code>int32 total_seats = 3;</code>
     * @param value The totalSeats to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSeats(int value) {
      
      totalSeats_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_seats = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalSeats() {
      
      totalSeats_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object passengerId_ = "";
    /**
     * <code>string passenger_id = 4;</code>
     * @return The passengerId.
     */
    public java.lang.String getPassengerId() {
      java.lang.Object ref = passengerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        passengerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string passenger_id = 4;</code>
     * @return The bytes for passengerId.
     */
    public com.google.protobuf.ByteString
        getPassengerIdBytes() {
      java.lang.Object ref = passengerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passengerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string passenger_id = 4;</code>
     * @param value The passengerId to set.
     * @return This builder for chaining.
     */
    public Builder setPassengerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      passengerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string passenger_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassengerId() {
      
      passengerId_ = getDefaultInstance().getPassengerId();
      onChanged();
      return this;
    }
    /**
     * <code>string passenger_id = 4;</code>
     * @param value The bytes for passengerId to set.
     * @return This builder for chaining.
     */
    public Builder setPassengerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      passengerId_ = value;
      onChanged();
      return this;
    }

    private long tripId_ ;
    /**
     * <code>int64 trip_id = 5;</code>
     * @return The tripId.
     */
    @java.lang.Override
    public long getTripId() {
      return tripId_;
    }
    /**
     * <code>int64 trip_id = 5;</code>
     * @param value The tripId to set.
     * @return This builder for chaining.
     */
    public Builder setTripId(long value) {
      
      tripId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 trip_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTripId() {
      
      tripId_ = 0L;
      onChanged();
      return this;
    }

    private via.sep3.grpcserver.protobuf.ticketservices.LocationMessage pickup_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.grpcserver.protobuf.ticketservices.LocationMessage, via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder, via.sep3.grpcserver.protobuf.ticketservices.LocationMessageOrBuilder> pickupBuilder_;
    /**
     * <code>.LocationMessage pickup = 6;</code>
     * @return Whether the pickup field is set.
     */
    public boolean hasPickup() {
      return pickupBuilder_ != null || pickup_ != null;
    }
    /**
     * <code>.LocationMessage pickup = 6;</code>
     * @return The pickup.
     */
    public via.sep3.grpcserver.protobuf.ticketservices.LocationMessage getPickup() {
      if (pickupBuilder_ == null) {
        return pickup_ == null ? via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.getDefaultInstance() : pickup_;
      } else {
        return pickupBuilder_.getMessage();
      }
    }
    /**
     * <code>.LocationMessage pickup = 6;</code>
     */
    public Builder setPickup(via.sep3.grpcserver.protobuf.ticketservices.LocationMessage value) {
      if (pickupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pickup_ = value;
        onChanged();
      } else {
        pickupBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LocationMessage pickup = 6;</code>
     */
    public Builder setPickup(
        via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder builderForValue) {
      if (pickupBuilder_ == null) {
        pickup_ = builderForValue.build();
        onChanged();
      } else {
        pickupBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LocationMessage pickup = 6;</code>
     */
    public Builder mergePickup(via.sep3.grpcserver.protobuf.ticketservices.LocationMessage value) {
      if (pickupBuilder_ == null) {
        if (pickup_ != null) {
          pickup_ =
            via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.newBuilder(pickup_).mergeFrom(value).buildPartial();
        } else {
          pickup_ = value;
        }
        onChanged();
      } else {
        pickupBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LocationMessage pickup = 6;</code>
     */
    public Builder clearPickup() {
      if (pickupBuilder_ == null) {
        pickup_ = null;
        onChanged();
      } else {
        pickup_ = null;
        pickupBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LocationMessage pickup = 6;</code>
     */
    public via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder getPickupBuilder() {
      
      onChanged();
      return getPickupFieldBuilder().getBuilder();
    }
    /**
     * <code>.LocationMessage pickup = 6;</code>
     */
    public via.sep3.grpcserver.protobuf.ticketservices.LocationMessageOrBuilder getPickupOrBuilder() {
      if (pickupBuilder_ != null) {
        return pickupBuilder_.getMessageOrBuilder();
      } else {
        return pickup_ == null ?
            via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.getDefaultInstance() : pickup_;
      }
    }
    /**
     * <code>.LocationMessage pickup = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.grpcserver.protobuf.ticketservices.LocationMessage, via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder, via.sep3.grpcserver.protobuf.ticketservices.LocationMessageOrBuilder> 
        getPickupFieldBuilder() {
      if (pickupBuilder_ == null) {
        pickupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.grpcserver.protobuf.ticketservices.LocationMessage, via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder, via.sep3.grpcserver.protobuf.ticketservices.LocationMessageOrBuilder>(
                getPickup(),
                getParentForChildren(),
                isClean());
        pickup_ = null;
      }
      return pickupBuilder_;
    }

    private via.sep3.grpcserver.protobuf.ticketservices.LocationMessage dropoff_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.grpcserver.protobuf.ticketservices.LocationMessage, via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder, via.sep3.grpcserver.protobuf.ticketservices.LocationMessageOrBuilder> dropoffBuilder_;
    /**
     * <code>.LocationMessage dropoff = 7;</code>
     * @return Whether the dropoff field is set.
     */
    public boolean hasDropoff() {
      return dropoffBuilder_ != null || dropoff_ != null;
    }
    /**
     * <code>.LocationMessage dropoff = 7;</code>
     * @return The dropoff.
     */
    public via.sep3.grpcserver.protobuf.ticketservices.LocationMessage getDropoff() {
      if (dropoffBuilder_ == null) {
        return dropoff_ == null ? via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.getDefaultInstance() : dropoff_;
      } else {
        return dropoffBuilder_.getMessage();
      }
    }
    /**
     * <code>.LocationMessage dropoff = 7;</code>
     */
    public Builder setDropoff(via.sep3.grpcserver.protobuf.ticketservices.LocationMessage value) {
      if (dropoffBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dropoff_ = value;
        onChanged();
      } else {
        dropoffBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LocationMessage dropoff = 7;</code>
     */
    public Builder setDropoff(
        via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder builderForValue) {
      if (dropoffBuilder_ == null) {
        dropoff_ = builderForValue.build();
        onChanged();
      } else {
        dropoffBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LocationMessage dropoff = 7;</code>
     */
    public Builder mergeDropoff(via.sep3.grpcserver.protobuf.ticketservices.LocationMessage value) {
      if (dropoffBuilder_ == null) {
        if (dropoff_ != null) {
          dropoff_ =
            via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.newBuilder(dropoff_).mergeFrom(value).buildPartial();
        } else {
          dropoff_ = value;
        }
        onChanged();
      } else {
        dropoffBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LocationMessage dropoff = 7;</code>
     */
    public Builder clearDropoff() {
      if (dropoffBuilder_ == null) {
        dropoff_ = null;
        onChanged();
      } else {
        dropoff_ = null;
        dropoffBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LocationMessage dropoff = 7;</code>
     */
    public via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder getDropoffBuilder() {
      
      onChanged();
      return getDropoffFieldBuilder().getBuilder();
    }
    /**
     * <code>.LocationMessage dropoff = 7;</code>
     */
    public via.sep3.grpcserver.protobuf.ticketservices.LocationMessageOrBuilder getDropoffOrBuilder() {
      if (dropoffBuilder_ != null) {
        return dropoffBuilder_.getMessageOrBuilder();
      } else {
        return dropoff_ == null ?
            via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.getDefaultInstance() : dropoff_;
      }
    }
    /**
     * <code>.LocationMessage dropoff = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.grpcserver.protobuf.ticketservices.LocationMessage, via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder, via.sep3.grpcserver.protobuf.ticketservices.LocationMessageOrBuilder> 
        getDropoffFieldBuilder() {
      if (dropoffBuilder_ == null) {
        dropoffBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.grpcserver.protobuf.ticketservices.LocationMessage, via.sep3.grpcserver.protobuf.ticketservices.LocationMessage.Builder, via.sep3.grpcserver.protobuf.ticketservices.LocationMessageOrBuilder>(
                getDropoff(),
                getParentForChildren(),
                isClean());
        dropoff_ = null;
      }
      return dropoffBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SeatTicketResponse)
  }

  // @@protoc_insertion_point(class_scope:SeatTicketResponse)
  private static final via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse();
  }

  public static via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SeatTicketResponse>
      PARSER = new com.google.protobuf.AbstractParser<SeatTicketResponse>() {
    @java.lang.Override
    public SeatTicketResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SeatTicketResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SeatTicketResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SeatTicketResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.grpcserver.protobuf.ticketservices.SeatTicketResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

