// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket.proto

package via.sep3.grpcserver.protobuf.ticketservices;

public interface TicketEmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TicketEmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
