// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package via.sep3.grpcserver.protobuf.carservices;

public final class Car {
  private Car() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestCarInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestCarInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseCarInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseCarInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcar.proto\"\212\001\n\016RequestCarInfo\022\r\n\005model\030" +
      "\001 \001(\t\022\r\n\005color\030\002 \001(\t\022\024\n\014plate_number\030\003 \001" +
      "(\t\022\023\n\013seats_count\030\004 \001(\005\022\021\n\tfuel_type\030\005 \001" +
      "(\t\022\034\n\024driver_drive_license\030\006 \001(\t\"m\n\017Resp" +
      "onseCarInfo\022\r\n\005model\030\001 \001(\t\022\r\n\005color\030\002 \001(" +
      "\t\022\024\n\014plate_number\030\003 \001(\t\022\023\n\013seats_count\030\004" +
      " \001(\005\022\021\n\tfuel_type\030\005 \001(\t\"0\n\rErrorResponse" +
      "\022\016\n\006status\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2=\n\013Car" +
      "Services\022.\n\tcreateCar\022\017.RequestCarInfo\032\020" +
      ".ResponseCarInfoB,\n(via.sep3.grpcserver." +
      "protobuf.carservicesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestCarInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestCarInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestCarInfo_descriptor,
        new java.lang.String[] { "Model", "Color", "PlateNumber", "SeatsCount", "FuelType", "DriverDriveLicense", });
    internal_static_ResponseCarInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseCarInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseCarInfo_descriptor,
        new java.lang.String[] { "Model", "Color", "PlateNumber", "SeatsCount", "FuelType", });
    internal_static_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrorResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
