// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating.proto

package via.sep3.grpcserver.protobuf.ratingservices;

/**
 * Protobuf type {@code RatingResponseMultiple}
 */
public final class RatingResponseMultiple extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RatingResponseMultiple)
    RatingResponseMultipleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RatingResponseMultiple.newBuilder() to construct.
  private RatingResponseMultiple(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RatingResponseMultiple() {
    ratings_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RatingResponseMultiple();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RatingResponseMultiple(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              ratings_ = new java.util.ArrayList<via.sep3.grpcserver.protobuf.ratingservices.RatingResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            ratings_.add(
                input.readMessage(via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        ratings_ = java.util.Collections.unmodifiableList(ratings_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.grpcserver.protobuf.ratingservices.Rating.internal_static_RatingResponseMultiple_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.grpcserver.protobuf.ratingservices.Rating.internal_static_RatingResponseMultiple_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple.class, via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple.Builder.class);
  }

  public static final int RATINGS_FIELD_NUMBER = 1;
  private java.util.List<via.sep3.grpcserver.protobuf.ratingservices.RatingResponse> ratings_;
  /**
   * <code>repeated .RatingResponse ratings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sep3.grpcserver.protobuf.ratingservices.RatingResponse> getRatingsList() {
    return ratings_;
  }
  /**
   * <code>repeated .RatingResponse ratings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sep3.grpcserver.protobuf.ratingservices.RatingResponseOrBuilder> 
      getRatingsOrBuilderList() {
    return ratings_;
  }
  /**
   * <code>repeated .RatingResponse ratings = 1;</code>
   */
  @java.lang.Override
  public int getRatingsCount() {
    return ratings_.size();
  }
  /**
   * <code>repeated .RatingResponse ratings = 1;</code>
   */
  @java.lang.Override
  public via.sep3.grpcserver.protobuf.ratingservices.RatingResponse getRatings(int index) {
    return ratings_.get(index);
  }
  /**
   * <code>repeated .RatingResponse ratings = 1;</code>
   */
  @java.lang.Override
  public via.sep3.grpcserver.protobuf.ratingservices.RatingResponseOrBuilder getRatingsOrBuilder(
      int index) {
    return ratings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ratings_.size(); i++) {
      output.writeMessage(1, ratings_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ratings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ratings_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple)) {
      return super.equals(obj);
    }
    via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple other = (via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple) obj;

    if (!getRatingsList()
        .equals(other.getRatingsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRatingsCount() > 0) {
      hash = (37 * hash) + RATINGS_FIELD_NUMBER;
      hash = (53 * hash) + getRatingsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RatingResponseMultiple}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RatingResponseMultiple)
      via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultipleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.grpcserver.protobuf.ratingservices.Rating.internal_static_RatingResponseMultiple_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.grpcserver.protobuf.ratingservices.Rating.internal_static_RatingResponseMultiple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple.class, via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple.Builder.class);
    }

    // Construct using via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRatingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (ratingsBuilder_ == null) {
        ratings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ratingsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.grpcserver.protobuf.ratingservices.Rating.internal_static_RatingResponseMultiple_descriptor;
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple getDefaultInstanceForType() {
      return via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple build() {
      via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple buildPartial() {
      via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple result = new via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple(this);
      int from_bitField0_ = bitField0_;
      if (ratingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          ratings_ = java.util.Collections.unmodifiableList(ratings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ratings_ = ratings_;
      } else {
        result.ratings_ = ratingsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple) {
        return mergeFrom((via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple other) {
      if (other == via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple.getDefaultInstance()) return this;
      if (ratingsBuilder_ == null) {
        if (!other.ratings_.isEmpty()) {
          if (ratings_.isEmpty()) {
            ratings_ = other.ratings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRatingsIsMutable();
            ratings_.addAll(other.ratings_);
          }
          onChanged();
        }
      } else {
        if (!other.ratings_.isEmpty()) {
          if (ratingsBuilder_.isEmpty()) {
            ratingsBuilder_.dispose();
            ratingsBuilder_ = null;
            ratings_ = other.ratings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ratingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRatingsFieldBuilder() : null;
          } else {
            ratingsBuilder_.addAllMessages(other.ratings_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sep3.grpcserver.protobuf.ratingservices.RatingResponse> ratings_ =
      java.util.Collections.emptyList();
    private void ensureRatingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ratings_ = new java.util.ArrayList<via.sep3.grpcserver.protobuf.ratingservices.RatingResponse>(ratings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.grpcserver.protobuf.ratingservices.RatingResponse, via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.Builder, via.sep3.grpcserver.protobuf.ratingservices.RatingResponseOrBuilder> ratingsBuilder_;

    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public java.util.List<via.sep3.grpcserver.protobuf.ratingservices.RatingResponse> getRatingsList() {
      if (ratingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ratings_);
      } else {
        return ratingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public int getRatingsCount() {
      if (ratingsBuilder_ == null) {
        return ratings_.size();
      } else {
        return ratingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public via.sep3.grpcserver.protobuf.ratingservices.RatingResponse getRatings(int index) {
      if (ratingsBuilder_ == null) {
        return ratings_.get(index);
      } else {
        return ratingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public Builder setRatings(
        int index, via.sep3.grpcserver.protobuf.ratingservices.RatingResponse value) {
      if (ratingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatingsIsMutable();
        ratings_.set(index, value);
        onChanged();
      } else {
        ratingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public Builder setRatings(
        int index, via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.Builder builderForValue) {
      if (ratingsBuilder_ == null) {
        ensureRatingsIsMutable();
        ratings_.set(index, builderForValue.build());
        onChanged();
      } else {
        ratingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public Builder addRatings(via.sep3.grpcserver.protobuf.ratingservices.RatingResponse value) {
      if (ratingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatingsIsMutable();
        ratings_.add(value);
        onChanged();
      } else {
        ratingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public Builder addRatings(
        int index, via.sep3.grpcserver.protobuf.ratingservices.RatingResponse value) {
      if (ratingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatingsIsMutable();
        ratings_.add(index, value);
        onChanged();
      } else {
        ratingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public Builder addRatings(
        via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.Builder builderForValue) {
      if (ratingsBuilder_ == null) {
        ensureRatingsIsMutable();
        ratings_.add(builderForValue.build());
        onChanged();
      } else {
        ratingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public Builder addRatings(
        int index, via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.Builder builderForValue) {
      if (ratingsBuilder_ == null) {
        ensureRatingsIsMutable();
        ratings_.add(index, builderForValue.build());
        onChanged();
      } else {
        ratingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public Builder addAllRatings(
        java.lang.Iterable<? extends via.sep3.grpcserver.protobuf.ratingservices.RatingResponse> values) {
      if (ratingsBuilder_ == null) {
        ensureRatingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ratings_);
        onChanged();
      } else {
        ratingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public Builder clearRatings() {
      if (ratingsBuilder_ == null) {
        ratings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ratingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public Builder removeRatings(int index) {
      if (ratingsBuilder_ == null) {
        ensureRatingsIsMutable();
        ratings_.remove(index);
        onChanged();
      } else {
        ratingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.Builder getRatingsBuilder(
        int index) {
      return getRatingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public via.sep3.grpcserver.protobuf.ratingservices.RatingResponseOrBuilder getRatingsOrBuilder(
        int index) {
      if (ratingsBuilder_ == null) {
        return ratings_.get(index);  } else {
        return ratingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public java.util.List<? extends via.sep3.grpcserver.protobuf.ratingservices.RatingResponseOrBuilder> 
         getRatingsOrBuilderList() {
      if (ratingsBuilder_ != null) {
        return ratingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ratings_);
      }
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.Builder addRatingsBuilder() {
      return getRatingsFieldBuilder().addBuilder(
          via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.Builder addRatingsBuilder(
        int index) {
      return getRatingsFieldBuilder().addBuilder(
          index, via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .RatingResponse ratings = 1;</code>
     */
    public java.util.List<via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.Builder> 
         getRatingsBuilderList() {
      return getRatingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.grpcserver.protobuf.ratingservices.RatingResponse, via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.Builder, via.sep3.grpcserver.protobuf.ratingservices.RatingResponseOrBuilder> 
        getRatingsFieldBuilder() {
      if (ratingsBuilder_ == null) {
        ratingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sep3.grpcserver.protobuf.ratingservices.RatingResponse, via.sep3.grpcserver.protobuf.ratingservices.RatingResponse.Builder, via.sep3.grpcserver.protobuf.ratingservices.RatingResponseOrBuilder>(
                ratings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        ratings_ = null;
      }
      return ratingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RatingResponseMultiple)
  }

  // @@protoc_insertion_point(class_scope:RatingResponseMultiple)
  private static final via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple();
  }

  public static via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RatingResponseMultiple>
      PARSER = new com.google.protobuf.AbstractParser<RatingResponseMultiple>() {
    @java.lang.Override
    public RatingResponseMultiple parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RatingResponseMultiple(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RatingResponseMultiple> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RatingResponseMultiple> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.grpcserver.protobuf.ratingservices.RatingResponseMultiple getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

