// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating.proto

package via.sep3.grpcserver.protobuf.ratingservices;

/**
 * Protobuf type {@code RatingCreationRequest}
 */
public final class RatingCreationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RatingCreationRequest)
    RatingCreationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RatingCreationRequest.newBuilder() to construct.
  private RatingCreationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RatingCreationRequest() {
    writerEmail_ = "";
    subjectEmail_ = "";
    ratingComment_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RatingCreationRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RatingCreationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            writerEmail_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            subjectEmail_ = s;
            break;
          }
          case 24: {

            rating_ = input.readSInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            ratingComment_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.grpcserver.protobuf.ratingservices.Rating.internal_static_RatingCreationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.grpcserver.protobuf.ratingservices.Rating.internal_static_RatingCreationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest.class, via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest.Builder.class);
  }

  public static final int WRITER_EMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object writerEmail_;
  /**
   * <code>string writer_email = 1;</code>
   * @return The writerEmail.
   */
  @java.lang.Override
  public java.lang.String getWriterEmail() {
    java.lang.Object ref = writerEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      writerEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string writer_email = 1;</code>
   * @return The bytes for writerEmail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWriterEmailBytes() {
    java.lang.Object ref = writerEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      writerEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBJECT_EMAIL_FIELD_NUMBER = 2;
  private volatile java.lang.Object subjectEmail_;
  /**
   * <code>string subject_email = 2;</code>
   * @return The subjectEmail.
   */
  @java.lang.Override
  public java.lang.String getSubjectEmail() {
    java.lang.Object ref = subjectEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subjectEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string subject_email = 2;</code>
   * @return The bytes for subjectEmail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectEmailBytes() {
    java.lang.Object ref = subjectEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subjectEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RATING_FIELD_NUMBER = 3;
  private int rating_;
  /**
   * <code>sint32 rating = 3;</code>
   * @return The rating.
   */
  @java.lang.Override
  public int getRating() {
    return rating_;
  }

  public static final int RATING_COMMENT_FIELD_NUMBER = 4;
  private volatile java.lang.Object ratingComment_;
  /**
   * <code>string rating_comment = 4;</code>
   * @return The ratingComment.
   */
  @java.lang.Override
  public java.lang.String getRatingComment() {
    java.lang.Object ref = ratingComment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ratingComment_ = s;
      return s;
    }
  }
  /**
   * <code>string rating_comment = 4;</code>
   * @return The bytes for ratingComment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRatingCommentBytes() {
    java.lang.Object ref = ratingComment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ratingComment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(writerEmail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, writerEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subjectEmail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subjectEmail_);
    }
    if (rating_ != 0) {
      output.writeSInt32(3, rating_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ratingComment_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ratingComment_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(writerEmail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, writerEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subjectEmail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subjectEmail_);
    }
    if (rating_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(3, rating_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ratingComment_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ratingComment_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest)) {
      return super.equals(obj);
    }
    via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest other = (via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest) obj;

    if (!getWriterEmail()
        .equals(other.getWriterEmail())) return false;
    if (!getSubjectEmail()
        .equals(other.getSubjectEmail())) return false;
    if (getRating()
        != other.getRating()) return false;
    if (!getRatingComment()
        .equals(other.getRatingComment())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WRITER_EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getWriterEmail().hashCode();
    hash = (37 * hash) + SUBJECT_EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getSubjectEmail().hashCode();
    hash = (37 * hash) + RATING_FIELD_NUMBER;
    hash = (53 * hash) + getRating();
    hash = (37 * hash) + RATING_COMMENT_FIELD_NUMBER;
    hash = (53 * hash) + getRatingComment().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RatingCreationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RatingCreationRequest)
      via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.grpcserver.protobuf.ratingservices.Rating.internal_static_RatingCreationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.grpcserver.protobuf.ratingservices.Rating.internal_static_RatingCreationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest.class, via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest.Builder.class);
    }

    // Construct using via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      writerEmail_ = "";

      subjectEmail_ = "";

      rating_ = 0;

      ratingComment_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.grpcserver.protobuf.ratingservices.Rating.internal_static_RatingCreationRequest_descriptor;
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest getDefaultInstanceForType() {
      return via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest build() {
      via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest buildPartial() {
      via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest result = new via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest(this);
      result.writerEmail_ = writerEmail_;
      result.subjectEmail_ = subjectEmail_;
      result.rating_ = rating_;
      result.ratingComment_ = ratingComment_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest) {
        return mergeFrom((via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest other) {
      if (other == via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest.getDefaultInstance()) return this;
      if (!other.getWriterEmail().isEmpty()) {
        writerEmail_ = other.writerEmail_;
        onChanged();
      }
      if (!other.getSubjectEmail().isEmpty()) {
        subjectEmail_ = other.subjectEmail_;
        onChanged();
      }
      if (other.getRating() != 0) {
        setRating(other.getRating());
      }
      if (!other.getRatingComment().isEmpty()) {
        ratingComment_ = other.ratingComment_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object writerEmail_ = "";
    /**
     * <code>string writer_email = 1;</code>
     * @return The writerEmail.
     */
    public java.lang.String getWriterEmail() {
      java.lang.Object ref = writerEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        writerEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string writer_email = 1;</code>
     * @return The bytes for writerEmail.
     */
    public com.google.protobuf.ByteString
        getWriterEmailBytes() {
      java.lang.Object ref = writerEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        writerEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string writer_email = 1;</code>
     * @param value The writerEmail to set.
     * @return This builder for chaining.
     */
    public Builder setWriterEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      writerEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string writer_email = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWriterEmail() {
      
      writerEmail_ = getDefaultInstance().getWriterEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string writer_email = 1;</code>
     * @param value The bytes for writerEmail to set.
     * @return This builder for chaining.
     */
    public Builder setWriterEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      writerEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object subjectEmail_ = "";
    /**
     * <code>string subject_email = 2;</code>
     * @return The subjectEmail.
     */
    public java.lang.String getSubjectEmail() {
      java.lang.Object ref = subjectEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subjectEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subject_email = 2;</code>
     * @return The bytes for subjectEmail.
     */
    public com.google.protobuf.ByteString
        getSubjectEmailBytes() {
      java.lang.Object ref = subjectEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subjectEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subject_email = 2;</code>
     * @param value The subjectEmail to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subjectEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string subject_email = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubjectEmail() {
      
      subjectEmail_ = getDefaultInstance().getSubjectEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string subject_email = 2;</code>
     * @param value The bytes for subjectEmail to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subjectEmail_ = value;
      onChanged();
      return this;
    }

    private int rating_ ;
    /**
     * <code>sint32 rating = 3;</code>
     * @return The rating.
     */
    @java.lang.Override
    public int getRating() {
      return rating_;
    }
    /**
     * <code>sint32 rating = 3;</code>
     * @param value The rating to set.
     * @return This builder for chaining.
     */
    public Builder setRating(int value) {
      
      rating_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 rating = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRating() {
      
      rating_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object ratingComment_ = "";
    /**
     * <code>string rating_comment = 4;</code>
     * @return The ratingComment.
     */
    public java.lang.String getRatingComment() {
      java.lang.Object ref = ratingComment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ratingComment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string rating_comment = 4;</code>
     * @return The bytes for ratingComment.
     */
    public com.google.protobuf.ByteString
        getRatingCommentBytes() {
      java.lang.Object ref = ratingComment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ratingComment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string rating_comment = 4;</code>
     * @param value The ratingComment to set.
     * @return This builder for chaining.
     */
    public Builder setRatingComment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ratingComment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string rating_comment = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRatingComment() {
      
      ratingComment_ = getDefaultInstance().getRatingComment();
      onChanged();
      return this;
    }
    /**
     * <code>string rating_comment = 4;</code>
     * @param value The bytes for ratingComment to set.
     * @return This builder for chaining.
     */
    public Builder setRatingCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ratingComment_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RatingCreationRequest)
  }

  // @@protoc_insertion_point(class_scope:RatingCreationRequest)
  private static final via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest();
  }

  public static via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RatingCreationRequest>
      PARSER = new com.google.protobuf.AbstractParser<RatingCreationRequest>() {
    @java.lang.Override
    public RatingCreationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RatingCreationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RatingCreationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RatingCreationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.grpcserver.protobuf.ratingservices.RatingCreationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

