// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating.proto

package via.sep3.grpcserver.protobuf.ratingservices;

public interface RatingCreationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RatingCreationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string writer_email = 1;</code>
   * @return The writerEmail.
   */
  java.lang.String getWriterEmail();
  /**
   * <code>string writer_email = 1;</code>
   * @return The bytes for writerEmail.
   */
  com.google.protobuf.ByteString
      getWriterEmailBytes();

  /**
   * <code>string subject_email = 2;</code>
   * @return The subjectEmail.
   */
  java.lang.String getSubjectEmail();
  /**
   * <code>string subject_email = 2;</code>
   * @return The bytes for subjectEmail.
   */
  com.google.protobuf.ByteString
      getSubjectEmailBytes();

  /**
   * <code>sint32 rating = 3;</code>
   * @return The rating.
   */
  int getRating();

  /**
   * <code>string rating_comment = 4;</code>
   * @return The ratingComment.
   */
  java.lang.String getRatingComment();
  /**
   * <code>string rating_comment = 4;</code>
   * @return The bytes for ratingComment.
   */
  com.google.protobuf.ByteString
      getRatingCommentBytes();
}
