// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating.proto

package via.sep3.grpcserver.protobuf.ratingservices;

public interface RatingResponseMultipleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RatingResponseMultiple)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .RatingResponse ratings = 1;</code>
   */
  java.util.List<via.sep3.grpcserver.protobuf.ratingservices.RatingResponse> 
      getRatingsList();
  /**
   * <code>repeated .RatingResponse ratings = 1;</code>
   */
  via.sep3.grpcserver.protobuf.ratingservices.RatingResponse getRatings(int index);
  /**
   * <code>repeated .RatingResponse ratings = 1;</code>
   */
  int getRatingsCount();
  /**
   * <code>repeated .RatingResponse ratings = 1;</code>
   */
  java.util.List<? extends via.sep3.grpcserver.protobuf.ratingservices.RatingResponseOrBuilder> 
      getRatingsOrBuilderList();
  /**
   * <code>repeated .RatingResponse ratings = 1;</code>
   */
  via.sep3.grpcserver.protobuf.ratingservices.RatingResponseOrBuilder getRatingsOrBuilder(
      int index);
}
