// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating.proto

package via.sep3.grpcserver.protobuf.ratingservices;

public final class Rating {
  private Rating() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserEmailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserEmailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RatingIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RatingIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RatingCreationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RatingCreationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RatingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RatingResponseMultiple_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RatingResponseMultiple_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014rating.proto\"\017\n\rGetAllRequest\"!\n\020UserE" +
      "mailRequest\022\r\n\005email\030\001 \001(\t\"\035\n\017RatingIdRe" +
      "quest\022\n\n\002id\030\001 \001(\003\"l\n\025RatingCreationReque" +
      "st\022\024\n\014writer_email\030\001 \001(\t\022\025\n\rsubject_emai" +
      "l\030\002 \001(\t\022\016\n\006rating\030\003 \001(\021\022\026\n\016rating_commen" +
      "t\030\004 \001(\t\"x\n\016RatingResponse\022\021\n\trating_id\030\001" +
      " \001(\003\022\024\n\014writer_email\030\002 \001(\t\022\025\n\rsubject_em" +
      "ail\030\003 \001(\t\022\016\n\006rating\030\004 \001(\021\022\026\n\016rating_comm" +
      "ent\030\005 \001(\t\":\n\026RatingResponseMultiple\022 \n\007r" +
      "atings\030\001 \003(\0132\017.RatingResponse2\371\002\n\016Rating" +
      "Services\0227\n\014CreateRating\022\026.RatingCreatio" +
      "nRequest\032\017.RatingResponse\0222\n\rGetRatingBy" +
      "Id\022\020.RatingIdRequest\032\017.RatingResponse\0228\n" +
      "\rGetAllRatings\022\016.GetAllRequest\032\027.RatingR" +
      "esponseMultiple\022E\n\027GetRatingsByWriterEma" +
      "il\022\021.UserEmailRequest\032\027.RatingResponseMu" +
      "ltiple\022F\n\030GetRatingsBySubjectEmail\022\021.Use" +
      "rEmailRequest\032\027.RatingResponseMultiple\0221" +
      "\n\014DeleteRating\022\020.RatingIdRequest\032\017.Ratin" +
      "gResponseB/\n+via.sep3.grpcserver.protobu" +
      "f.ratingservicesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_UserEmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserEmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserEmailRequest_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_RatingIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RatingIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RatingIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_RatingCreationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RatingCreationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RatingCreationRequest_descriptor,
        new java.lang.String[] { "WriterEmail", "SubjectEmail", "Rating", "RatingComment", });
    internal_static_RatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RatingResponse_descriptor,
        new java.lang.String[] { "RatingId", "WriterEmail", "SubjectEmail", "Rating", "RatingComment", });
    internal_static_RatingResponseMultiple_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RatingResponseMultiple_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RatingResponseMultiple_descriptor,
        new java.lang.String[] { "Ratings", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
