// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trip.proto

package via.sep3.grpcserver.protobuf.tripservices;

public interface EmptymessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Emptymessage)
    com.google.protobuf.MessageOrBuilder {
}
