// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package via.sep3.grpcserver.protobuf.notificationservices;

/**
 * Protobuf type {@code Location}
 */
public final class Location extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Location)
    LocationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Location.newBuilder() to construct.
  private Location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Location() {
    postCode_ = "";
    city_ = "";
    streetName_ = "";
    streetNumber_ = "";
    arrivalTime_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Location();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Location(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            postCode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            streetName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            streetNumber_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            arrivalTime_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.grpcserver.protobuf.notificationservices.Notification.internal_static_Location_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.grpcserver.protobuf.notificationservices.Notification.internal_static_Location_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.grpcserver.protobuf.notificationservices.Location.class, via.sep3.grpcserver.protobuf.notificationservices.Location.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int POST_CODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object postCode_;
  /**
   * <code>string post_code = 2;</code>
   * @return The postCode.
   */
  @java.lang.Override
  public java.lang.String getPostCode() {
    java.lang.Object ref = postCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      postCode_ = s;
      return s;
    }
  }
  /**
   * <code>string post_code = 2;</code>
   * @return The bytes for postCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPostCodeBytes() {
    java.lang.Object ref = postCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      postCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITY_FIELD_NUMBER = 3;
  private volatile java.lang.Object city_;
  /**
   * <code>string city = 3;</code>
   * @return The city.
   */
  @java.lang.Override
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <code>string city = 3;</code>
   * @return The bytes for city.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREET_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object streetName_;
  /**
   * <code>string street_name = 4;</code>
   * @return The streetName.
   */
  @java.lang.Override
  public java.lang.String getStreetName() {
    java.lang.Object ref = streetName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      streetName_ = s;
      return s;
    }
  }
  /**
   * <code>string street_name = 4;</code>
   * @return The bytes for streetName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStreetNameBytes() {
    java.lang.Object ref = streetName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      streetName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREET_NUMBER_FIELD_NUMBER = 5;
  private volatile java.lang.Object streetNumber_;
  /**
   * <code>string street_number = 5;</code>
   * @return The streetNumber.
   */
  @java.lang.Override
  public java.lang.String getStreetNumber() {
    java.lang.Object ref = streetNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      streetNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string street_number = 5;</code>
   * @return The bytes for streetNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStreetNumberBytes() {
    java.lang.Object ref = streetNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      streetNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARRIVAL_TIME_FIELD_NUMBER = 6;
  private volatile java.lang.Object arrivalTime_;
  /**
   * <code>string arrival_time = 6;</code>
   * @return The arrivalTime.
   */
  @java.lang.Override
  public java.lang.String getArrivalTime() {
    java.lang.Object ref = arrivalTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arrivalTime_ = s;
      return s;
    }
  }
  /**
   * <code>string arrival_time = 6;</code>
   * @return The bytes for arrivalTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArrivalTimeBytes() {
    java.lang.Object ref = arrivalTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arrivalTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(postCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, postCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, city_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streetName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, streetName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streetNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, streetNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(arrivalTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, arrivalTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(postCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, postCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, city_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streetName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, streetName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streetNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, streetNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(arrivalTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, arrivalTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.grpcserver.protobuf.notificationservices.Location)) {
      return super.equals(obj);
    }
    via.sep3.grpcserver.protobuf.notificationservices.Location other = (via.sep3.grpcserver.protobuf.notificationservices.Location) obj;

    if (getId()
        != other.getId()) return false;
    if (!getPostCode()
        .equals(other.getPostCode())) return false;
    if (!getCity()
        .equals(other.getCity())) return false;
    if (!getStreetName()
        .equals(other.getStreetName())) return false;
    if (!getStreetNumber()
        .equals(other.getStreetNumber())) return false;
    if (!getArrivalTime()
        .equals(other.getArrivalTime())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + POST_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getPostCode().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + STREET_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getStreetName().hashCode();
    hash = (37 * hash) + STREET_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getStreetNumber().hashCode();
    hash = (37 * hash) + ARRIVAL_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getArrivalTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.Location parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.grpcserver.protobuf.notificationservices.Location prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Location}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Location)
      via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.grpcserver.protobuf.notificationservices.Notification.internal_static_Location_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.grpcserver.protobuf.notificationservices.Notification.internal_static_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.grpcserver.protobuf.notificationservices.Location.class, via.sep3.grpcserver.protobuf.notificationservices.Location.Builder.class);
    }

    // Construct using via.sep3.grpcserver.protobuf.notificationservices.Location.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      postCode_ = "";

      city_ = "";

      streetName_ = "";

      streetNumber_ = "";

      arrivalTime_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.grpcserver.protobuf.notificationservices.Notification.internal_static_Location_descriptor;
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.notificationservices.Location getDefaultInstanceForType() {
      return via.sep3.grpcserver.protobuf.notificationservices.Location.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.notificationservices.Location build() {
      via.sep3.grpcserver.protobuf.notificationservices.Location result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.notificationservices.Location buildPartial() {
      via.sep3.grpcserver.protobuf.notificationservices.Location result = new via.sep3.grpcserver.protobuf.notificationservices.Location(this);
      result.id_ = id_;
      result.postCode_ = postCode_;
      result.city_ = city_;
      result.streetName_ = streetName_;
      result.streetNumber_ = streetNumber_;
      result.arrivalTime_ = arrivalTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.grpcserver.protobuf.notificationservices.Location) {
        return mergeFrom((via.sep3.grpcserver.protobuf.notificationservices.Location)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.grpcserver.protobuf.notificationservices.Location other) {
      if (other == via.sep3.grpcserver.protobuf.notificationservices.Location.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getPostCode().isEmpty()) {
        postCode_ = other.postCode_;
        onChanged();
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (!other.getStreetName().isEmpty()) {
        streetName_ = other.streetName_;
        onChanged();
      }
      if (!other.getStreetNumber().isEmpty()) {
        streetNumber_ = other.streetNumber_;
        onChanged();
      }
      if (!other.getArrivalTime().isEmpty()) {
        arrivalTime_ = other.arrivalTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.grpcserver.protobuf.notificationservices.Location parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.grpcserver.protobuf.notificationservices.Location) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object postCode_ = "";
    /**
     * <code>string post_code = 2;</code>
     * @return The postCode.
     */
    public java.lang.String getPostCode() {
      java.lang.Object ref = postCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        postCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string post_code = 2;</code>
     * @return The bytes for postCode.
     */
    public com.google.protobuf.ByteString
        getPostCodeBytes() {
      java.lang.Object ref = postCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string post_code = 2;</code>
     * @param value The postCode to set.
     * @return This builder for chaining.
     */
    public Builder setPostCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      postCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string post_code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostCode() {
      
      postCode_ = getDefaultInstance().getPostCode();
      onChanged();
      return this;
    }
    /**
     * <code>string post_code = 2;</code>
     * @param value The bytes for postCode to set.
     * @return This builder for chaining.
     */
    public Builder setPostCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      postCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object city_ = "";
    /**
     * <code>string city = 3;</code>
     * @return The city.
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string city = 3;</code>
     * @return The bytes for city.
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string city = 3;</code>
     * @param value The city to set.
     * @return This builder for chaining.
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string city = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <code>string city = 3;</code>
     * @param value The bytes for city to set.
     * @return This builder for chaining.
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object streetName_ = "";
    /**
     * <code>string street_name = 4;</code>
     * @return The streetName.
     */
    public java.lang.String getStreetName() {
      java.lang.Object ref = streetName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string street_name = 4;</code>
     * @return The bytes for streetName.
     */
    public com.google.protobuf.ByteString
        getStreetNameBytes() {
      java.lang.Object ref = streetName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string street_name = 4;</code>
     * @param value The streetName to set.
     * @return This builder for chaining.
     */
    public Builder setStreetName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      streetName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string street_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreetName() {
      
      streetName_ = getDefaultInstance().getStreetName();
      onChanged();
      return this;
    }
    /**
     * <code>string street_name = 4;</code>
     * @param value The bytes for streetName to set.
     * @return This builder for chaining.
     */
    public Builder setStreetNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      streetName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object streetNumber_ = "";
    /**
     * <code>string street_number = 5;</code>
     * @return The streetNumber.
     */
    public java.lang.String getStreetNumber() {
      java.lang.Object ref = streetNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string street_number = 5;</code>
     * @return The bytes for streetNumber.
     */
    public com.google.protobuf.ByteString
        getStreetNumberBytes() {
      java.lang.Object ref = streetNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string street_number = 5;</code>
     * @param value The streetNumber to set.
     * @return This builder for chaining.
     */
    public Builder setStreetNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      streetNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string street_number = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreetNumber() {
      
      streetNumber_ = getDefaultInstance().getStreetNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string street_number = 5;</code>
     * @param value The bytes for streetNumber to set.
     * @return This builder for chaining.
     */
    public Builder setStreetNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      streetNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object arrivalTime_ = "";
    /**
     * <code>string arrival_time = 6;</code>
     * @return The arrivalTime.
     */
    public java.lang.String getArrivalTime() {
      java.lang.Object ref = arrivalTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arrivalTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arrival_time = 6;</code>
     * @return The bytes for arrivalTime.
     */
    public com.google.protobuf.ByteString
        getArrivalTimeBytes() {
      java.lang.Object ref = arrivalTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arrivalTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arrival_time = 6;</code>
     * @param value The arrivalTime to set.
     * @return This builder for chaining.
     */
    public Builder setArrivalTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arrivalTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string arrival_time = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearArrivalTime() {
      
      arrivalTime_ = getDefaultInstance().getArrivalTime();
      onChanged();
      return this;
    }
    /**
     * <code>string arrival_time = 6;</code>
     * @param value The bytes for arrivalTime to set.
     * @return This builder for chaining.
     */
    public Builder setArrivalTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arrivalTime_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Location)
  }

  // @@protoc_insertion_point(class_scope:Location)
  private static final via.sep3.grpcserver.protobuf.notificationservices.Location DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.grpcserver.protobuf.notificationservices.Location();
  }

  public static via.sep3.grpcserver.protobuf.notificationservices.Location getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Location>
      PARSER = new com.google.protobuf.AbstractParser<Location>() {
    @java.lang.Override
    public Location parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Location(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Location> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Location> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.grpcserver.protobuf.notificationservices.Location getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

