// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package via.sep3.grpcserver.protobuf.notificationservices;

public interface ResponseActiveNotificationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseActiveNotifications)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ReturnedNotification notifications = 1;</code>
   */
  java.util.List<via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification> 
      getNotificationsList();
  /**
   * <code>repeated .ReturnedNotification notifications = 1;</code>
   */
  via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification getNotifications(int index);
  /**
   * <code>repeated .ReturnedNotification notifications = 1;</code>
   */
  int getNotificationsCount();
  /**
   * <code>repeated .ReturnedNotification notifications = 1;</code>
   */
  java.util.List<? extends via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotificationOrBuilder> 
      getNotificationsOrBuilderList();
  /**
   * <code>repeated .ReturnedNotification notifications = 1;</code>
   */
  via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotificationOrBuilder getNotificationsOrBuilder(
      int index);
}
