// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package via.sep3.grpcserver.protobuf.notificationservices;

public interface ReturnedNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReturnedNotification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consumer_id = 1;</code>
   * @return The consumerId.
   */
  java.lang.String getConsumerId();
  /**
   * <code>string consumer_id = 1;</code>
   * @return The bytes for consumerId.
   */
  com.google.protobuf.ByteString
      getConsumerIdBytes();

  /**
   * <code>string sender_id = 2;</code>
   * @return The senderId.
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 2;</code>
   * @return The bytes for senderId.
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>.Location requested_pickup_location_id = 3;</code>
   * @return Whether the requestedPickupLocationId field is set.
   */
  boolean hasRequestedPickupLocationId();
  /**
   * <code>.Location requested_pickup_location_id = 3;</code>
   * @return The requestedPickupLocationId.
   */
  via.sep3.grpcserver.protobuf.notificationservices.Location getRequestedPickupLocationId();
  /**
   * <code>.Location requested_pickup_location_id = 3;</code>
   */
  via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder getRequestedPickupLocationIdOrBuilder();

  /**
   * <code>.Location requested_drop_location_id = 4;</code>
   * @return Whether the requestedDropLocationId field is set.
   */
  boolean hasRequestedDropLocationId();
  /**
   * <code>.Location requested_drop_location_id = 4;</code>
   * @return The requestedDropLocationId.
   */
  via.sep3.grpcserver.protobuf.notificationservices.Location getRequestedDropLocationId();
  /**
   * <code>.Location requested_drop_location_id = 4;</code>
   */
  via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder getRequestedDropLocationIdOrBuilder();

  /**
   * <code>double seat_price = 5;</code>
   * @return The seatPrice.
   */
  double getSeatPrice();

  /**
   * <code>int32 seat_count = 6;</code>
   * @return The seatCount.
   */
  int getSeatCount();

  /**
   * <code>string msg = 7;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 7;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>int32 id = 8;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 trip_id = 9;</code>
   * @return The tripId.
   */
  int getTripId();
}
