// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package via.sep3.grpcserver.protobuf.notificationservices;

/**
 * Protobuf type {@code ReturnedNotification}
 */
public final class ReturnedNotification extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReturnedNotification)
    ReturnedNotificationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReturnedNotification.newBuilder() to construct.
  private ReturnedNotification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReturnedNotification() {
    consumerId_ = "";
    senderId_ = "";
    msg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReturnedNotification();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReturnedNotification(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            consumerId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            senderId_ = s;
            break;
          }
          case 26: {
            via.sep3.grpcserver.protobuf.notificationservices.Location.Builder subBuilder = null;
            if (requestedPickupLocationId_ != null) {
              subBuilder = requestedPickupLocationId_.toBuilder();
            }
            requestedPickupLocationId_ = input.readMessage(via.sep3.grpcserver.protobuf.notificationservices.Location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(requestedPickupLocationId_);
              requestedPickupLocationId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            via.sep3.grpcserver.protobuf.notificationservices.Location.Builder subBuilder = null;
            if (requestedDropLocationId_ != null) {
              subBuilder = requestedDropLocationId_.toBuilder();
            }
            requestedDropLocationId_ = input.readMessage(via.sep3.grpcserver.protobuf.notificationservices.Location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(requestedDropLocationId_);
              requestedDropLocationId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 41: {

            seatPrice_ = input.readDouble();
            break;
          }
          case 48: {

            seatCount_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
          case 64: {

            id_ = input.readInt32();
            break;
          }
          case 72: {

            tripId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.grpcserver.protobuf.notificationservices.Notification.internal_static_ReturnedNotification_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.grpcserver.protobuf.notificationservices.Notification.internal_static_ReturnedNotification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification.class, via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification.Builder.class);
  }

  public static final int CONSUMER_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object consumerId_;
  /**
   * <code>string consumer_id = 1;</code>
   * @return The consumerId.
   */
  @java.lang.Override
  public java.lang.String getConsumerId() {
    java.lang.Object ref = consumerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      consumerId_ = s;
      return s;
    }
  }
  /**
   * <code>string consumer_id = 1;</code>
   * @return The bytes for consumerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConsumerIdBytes() {
    java.lang.Object ref = consumerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      consumerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDER_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object senderId_;
  /**
   * <code>string sender_id = 2;</code>
   * @return The senderId.
   */
  @java.lang.Override
  public java.lang.String getSenderId() {
    java.lang.Object ref = senderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderId_ = s;
      return s;
    }
  }
  /**
   * <code>string sender_id = 2;</code>
   * @return The bytes for senderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderIdBytes() {
    java.lang.Object ref = senderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTED_PICKUP_LOCATION_ID_FIELD_NUMBER = 3;
  private via.sep3.grpcserver.protobuf.notificationservices.Location requestedPickupLocationId_;
  /**
   * <code>.Location requested_pickup_location_id = 3;</code>
   * @return Whether the requestedPickupLocationId field is set.
   */
  @java.lang.Override
  public boolean hasRequestedPickupLocationId() {
    return requestedPickupLocationId_ != null;
  }
  /**
   * <code>.Location requested_pickup_location_id = 3;</code>
   * @return The requestedPickupLocationId.
   */
  @java.lang.Override
  public via.sep3.grpcserver.protobuf.notificationservices.Location getRequestedPickupLocationId() {
    return requestedPickupLocationId_ == null ? via.sep3.grpcserver.protobuf.notificationservices.Location.getDefaultInstance() : requestedPickupLocationId_;
  }
  /**
   * <code>.Location requested_pickup_location_id = 3;</code>
   */
  @java.lang.Override
  public via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder getRequestedPickupLocationIdOrBuilder() {
    return getRequestedPickupLocationId();
  }

  public static final int REQUESTED_DROP_LOCATION_ID_FIELD_NUMBER = 4;
  private via.sep3.grpcserver.protobuf.notificationservices.Location requestedDropLocationId_;
  /**
   * <code>.Location requested_drop_location_id = 4;</code>
   * @return Whether the requestedDropLocationId field is set.
   */
  @java.lang.Override
  public boolean hasRequestedDropLocationId() {
    return requestedDropLocationId_ != null;
  }
  /**
   * <code>.Location requested_drop_location_id = 4;</code>
   * @return The requestedDropLocationId.
   */
  @java.lang.Override
  public via.sep3.grpcserver.protobuf.notificationservices.Location getRequestedDropLocationId() {
    return requestedDropLocationId_ == null ? via.sep3.grpcserver.protobuf.notificationservices.Location.getDefaultInstance() : requestedDropLocationId_;
  }
  /**
   * <code>.Location requested_drop_location_id = 4;</code>
   */
  @java.lang.Override
  public via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder getRequestedDropLocationIdOrBuilder() {
    return getRequestedDropLocationId();
  }

  public static final int SEAT_PRICE_FIELD_NUMBER = 5;
  private double seatPrice_;
  /**
   * <code>double seat_price = 5;</code>
   * @return The seatPrice.
   */
  @java.lang.Override
  public double getSeatPrice() {
    return seatPrice_;
  }

  public static final int SEAT_COUNT_FIELD_NUMBER = 6;
  private int seatCount_;
  /**
   * <code>int32 seat_count = 6;</code>
   * @return The seatCount.
   */
  @java.lang.Override
  public int getSeatCount() {
    return seatCount_;
  }

  public static final int MSG_FIELD_NUMBER = 7;
  private volatile java.lang.Object msg_;
  /**
   * <code>string msg = 7;</code>
   * @return The msg.
   */
  @java.lang.Override
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>string msg = 7;</code>
   * @return The bytes for msg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 8;
  private int id_;
  /**
   * <code>int32 id = 8;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int TRIP_ID_FIELD_NUMBER = 9;
  private int tripId_;
  /**
   * <code>int32 trip_id = 9;</code>
   * @return The tripId.
   */
  @java.lang.Override
  public int getTripId() {
    return tripId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(consumerId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, consumerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderId_);
    }
    if (requestedPickupLocationId_ != null) {
      output.writeMessage(3, getRequestedPickupLocationId());
    }
    if (requestedDropLocationId_ != null) {
      output.writeMessage(4, getRequestedDropLocationId());
    }
    if (java.lang.Double.doubleToRawLongBits(seatPrice_) != 0) {
      output.writeDouble(5, seatPrice_);
    }
    if (seatCount_ != 0) {
      output.writeInt32(6, seatCount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msg_);
    }
    if (id_ != 0) {
      output.writeInt32(8, id_);
    }
    if (tripId_ != 0) {
      output.writeInt32(9, tripId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(consumerId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, consumerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderId_);
    }
    if (requestedPickupLocationId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRequestedPickupLocationId());
    }
    if (requestedDropLocationId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRequestedDropLocationId());
    }
    if (java.lang.Double.doubleToRawLongBits(seatPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, seatPrice_);
    }
    if (seatCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, seatCount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msg_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, id_);
    }
    if (tripId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, tripId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification)) {
      return super.equals(obj);
    }
    via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification other = (via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification) obj;

    if (!getConsumerId()
        .equals(other.getConsumerId())) return false;
    if (!getSenderId()
        .equals(other.getSenderId())) return false;
    if (hasRequestedPickupLocationId() != other.hasRequestedPickupLocationId()) return false;
    if (hasRequestedPickupLocationId()) {
      if (!getRequestedPickupLocationId()
          .equals(other.getRequestedPickupLocationId())) return false;
    }
    if (hasRequestedDropLocationId() != other.hasRequestedDropLocationId()) return false;
    if (hasRequestedDropLocationId()) {
      if (!getRequestedDropLocationId()
          .equals(other.getRequestedDropLocationId())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getSeatPrice())
        != java.lang.Double.doubleToLongBits(
            other.getSeatPrice())) return false;
    if (getSeatCount()
        != other.getSeatCount()) return false;
    if (!getMsg()
        .equals(other.getMsg())) return false;
    if (getId()
        != other.getId()) return false;
    if (getTripId()
        != other.getTripId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONSUMER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConsumerId().hashCode();
    hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderId().hashCode();
    if (hasRequestedPickupLocationId()) {
      hash = (37 * hash) + REQUESTED_PICKUP_LOCATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestedPickupLocationId().hashCode();
    }
    if (hasRequestedDropLocationId()) {
      hash = (37 * hash) + REQUESTED_DROP_LOCATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestedDropLocationId().hashCode();
    }
    hash = (37 * hash) + SEAT_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSeatPrice()));
    hash = (37 * hash) + SEAT_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getSeatCount();
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + TRIP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTripId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ReturnedNotification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReturnedNotification)
      via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.grpcserver.protobuf.notificationservices.Notification.internal_static_ReturnedNotification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.grpcserver.protobuf.notificationservices.Notification.internal_static_ReturnedNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification.class, via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification.Builder.class);
    }

    // Construct using via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      consumerId_ = "";

      senderId_ = "";

      if (requestedPickupLocationIdBuilder_ == null) {
        requestedPickupLocationId_ = null;
      } else {
        requestedPickupLocationId_ = null;
        requestedPickupLocationIdBuilder_ = null;
      }
      if (requestedDropLocationIdBuilder_ == null) {
        requestedDropLocationId_ = null;
      } else {
        requestedDropLocationId_ = null;
        requestedDropLocationIdBuilder_ = null;
      }
      seatPrice_ = 0D;

      seatCount_ = 0;

      msg_ = "";

      id_ = 0;

      tripId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.grpcserver.protobuf.notificationservices.Notification.internal_static_ReturnedNotification_descriptor;
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification getDefaultInstanceForType() {
      return via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification build() {
      via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification buildPartial() {
      via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification result = new via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification(this);
      result.consumerId_ = consumerId_;
      result.senderId_ = senderId_;
      if (requestedPickupLocationIdBuilder_ == null) {
        result.requestedPickupLocationId_ = requestedPickupLocationId_;
      } else {
        result.requestedPickupLocationId_ = requestedPickupLocationIdBuilder_.build();
      }
      if (requestedDropLocationIdBuilder_ == null) {
        result.requestedDropLocationId_ = requestedDropLocationId_;
      } else {
        result.requestedDropLocationId_ = requestedDropLocationIdBuilder_.build();
      }
      result.seatPrice_ = seatPrice_;
      result.seatCount_ = seatCount_;
      result.msg_ = msg_;
      result.id_ = id_;
      result.tripId_ = tripId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification) {
        return mergeFrom((via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification other) {
      if (other == via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification.getDefaultInstance()) return this;
      if (!other.getConsumerId().isEmpty()) {
        consumerId_ = other.consumerId_;
        onChanged();
      }
      if (!other.getSenderId().isEmpty()) {
        senderId_ = other.senderId_;
        onChanged();
      }
      if (other.hasRequestedPickupLocationId()) {
        mergeRequestedPickupLocationId(other.getRequestedPickupLocationId());
      }
      if (other.hasRequestedDropLocationId()) {
        mergeRequestedDropLocationId(other.getRequestedDropLocationId());
      }
      if (other.getSeatPrice() != 0D) {
        setSeatPrice(other.getSeatPrice());
      }
      if (other.getSeatCount() != 0) {
        setSeatCount(other.getSeatCount());
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getTripId() != 0) {
        setTripId(other.getTripId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object consumerId_ = "";
    /**
     * <code>string consumer_id = 1;</code>
     * @return The consumerId.
     */
    public java.lang.String getConsumerId() {
      java.lang.Object ref = consumerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @return The bytes for consumerId.
     */
    public com.google.protobuf.ByteString
        getConsumerIdBytes() {
      java.lang.Object ref = consumerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @param value The consumerId to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      consumerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConsumerId() {
      
      consumerId_ = getDefaultInstance().getConsumerId();
      onChanged();
      return this;
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @param value The bytes for consumerId to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      consumerId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object senderId_ = "";
    /**
     * <code>string sender_id = 2;</code>
     * @return The senderId.
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender_id = 2;</code>
     * @return The bytes for senderId.
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender_id = 2;</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sender_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      
      senderId_ = getDefaultInstance().getSenderId();
      onChanged();
      return this;
    }
    /**
     * <code>string sender_id = 2;</code>
     * @param value The bytes for senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderId_ = value;
      onChanged();
      return this;
    }

    private via.sep3.grpcserver.protobuf.notificationservices.Location requestedPickupLocationId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.grpcserver.protobuf.notificationservices.Location, via.sep3.grpcserver.protobuf.notificationservices.Location.Builder, via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder> requestedPickupLocationIdBuilder_;
    /**
     * <code>.Location requested_pickup_location_id = 3;</code>
     * @return Whether the requestedPickupLocationId field is set.
     */
    public boolean hasRequestedPickupLocationId() {
      return requestedPickupLocationIdBuilder_ != null || requestedPickupLocationId_ != null;
    }
    /**
     * <code>.Location requested_pickup_location_id = 3;</code>
     * @return The requestedPickupLocationId.
     */
    public via.sep3.grpcserver.protobuf.notificationservices.Location getRequestedPickupLocationId() {
      if (requestedPickupLocationIdBuilder_ == null) {
        return requestedPickupLocationId_ == null ? via.sep3.grpcserver.protobuf.notificationservices.Location.getDefaultInstance() : requestedPickupLocationId_;
      } else {
        return requestedPickupLocationIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.Location requested_pickup_location_id = 3;</code>
     */
    public Builder setRequestedPickupLocationId(via.sep3.grpcserver.protobuf.notificationservices.Location value) {
      if (requestedPickupLocationIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestedPickupLocationId_ = value;
        onChanged();
      } else {
        requestedPickupLocationIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Location requested_pickup_location_id = 3;</code>
     */
    public Builder setRequestedPickupLocationId(
        via.sep3.grpcserver.protobuf.notificationservices.Location.Builder builderForValue) {
      if (requestedPickupLocationIdBuilder_ == null) {
        requestedPickupLocationId_ = builderForValue.build();
        onChanged();
      } else {
        requestedPickupLocationIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Location requested_pickup_location_id = 3;</code>
     */
    public Builder mergeRequestedPickupLocationId(via.sep3.grpcserver.protobuf.notificationservices.Location value) {
      if (requestedPickupLocationIdBuilder_ == null) {
        if (requestedPickupLocationId_ != null) {
          requestedPickupLocationId_ =
            via.sep3.grpcserver.protobuf.notificationservices.Location.newBuilder(requestedPickupLocationId_).mergeFrom(value).buildPartial();
        } else {
          requestedPickupLocationId_ = value;
        }
        onChanged();
      } else {
        requestedPickupLocationIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Location requested_pickup_location_id = 3;</code>
     */
    public Builder clearRequestedPickupLocationId() {
      if (requestedPickupLocationIdBuilder_ == null) {
        requestedPickupLocationId_ = null;
        onChanged();
      } else {
        requestedPickupLocationId_ = null;
        requestedPickupLocationIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Location requested_pickup_location_id = 3;</code>
     */
    public via.sep3.grpcserver.protobuf.notificationservices.Location.Builder getRequestedPickupLocationIdBuilder() {
      
      onChanged();
      return getRequestedPickupLocationIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.Location requested_pickup_location_id = 3;</code>
     */
    public via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder getRequestedPickupLocationIdOrBuilder() {
      if (requestedPickupLocationIdBuilder_ != null) {
        return requestedPickupLocationIdBuilder_.getMessageOrBuilder();
      } else {
        return requestedPickupLocationId_ == null ?
            via.sep3.grpcserver.protobuf.notificationservices.Location.getDefaultInstance() : requestedPickupLocationId_;
      }
    }
    /**
     * <code>.Location requested_pickup_location_id = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.grpcserver.protobuf.notificationservices.Location, via.sep3.grpcserver.protobuf.notificationservices.Location.Builder, via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder> 
        getRequestedPickupLocationIdFieldBuilder() {
      if (requestedPickupLocationIdBuilder_ == null) {
        requestedPickupLocationIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.grpcserver.protobuf.notificationservices.Location, via.sep3.grpcserver.protobuf.notificationservices.Location.Builder, via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder>(
                getRequestedPickupLocationId(),
                getParentForChildren(),
                isClean());
        requestedPickupLocationId_ = null;
      }
      return requestedPickupLocationIdBuilder_;
    }

    private via.sep3.grpcserver.protobuf.notificationservices.Location requestedDropLocationId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.grpcserver.protobuf.notificationservices.Location, via.sep3.grpcserver.protobuf.notificationservices.Location.Builder, via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder> requestedDropLocationIdBuilder_;
    /**
     * <code>.Location requested_drop_location_id = 4;</code>
     * @return Whether the requestedDropLocationId field is set.
     */
    public boolean hasRequestedDropLocationId() {
      return requestedDropLocationIdBuilder_ != null || requestedDropLocationId_ != null;
    }
    /**
     * <code>.Location requested_drop_location_id = 4;</code>
     * @return The requestedDropLocationId.
     */
    public via.sep3.grpcserver.protobuf.notificationservices.Location getRequestedDropLocationId() {
      if (requestedDropLocationIdBuilder_ == null) {
        return requestedDropLocationId_ == null ? via.sep3.grpcserver.protobuf.notificationservices.Location.getDefaultInstance() : requestedDropLocationId_;
      } else {
        return requestedDropLocationIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.Location requested_drop_location_id = 4;</code>
     */
    public Builder setRequestedDropLocationId(via.sep3.grpcserver.protobuf.notificationservices.Location value) {
      if (requestedDropLocationIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestedDropLocationId_ = value;
        onChanged();
      } else {
        requestedDropLocationIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Location requested_drop_location_id = 4;</code>
     */
    public Builder setRequestedDropLocationId(
        via.sep3.grpcserver.protobuf.notificationservices.Location.Builder builderForValue) {
      if (requestedDropLocationIdBuilder_ == null) {
        requestedDropLocationId_ = builderForValue.build();
        onChanged();
      } else {
        requestedDropLocationIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Location requested_drop_location_id = 4;</code>
     */
    public Builder mergeRequestedDropLocationId(via.sep3.grpcserver.protobuf.notificationservices.Location value) {
      if (requestedDropLocationIdBuilder_ == null) {
        if (requestedDropLocationId_ != null) {
          requestedDropLocationId_ =
            via.sep3.grpcserver.protobuf.notificationservices.Location.newBuilder(requestedDropLocationId_).mergeFrom(value).buildPartial();
        } else {
          requestedDropLocationId_ = value;
        }
        onChanged();
      } else {
        requestedDropLocationIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Location requested_drop_location_id = 4;</code>
     */
    public Builder clearRequestedDropLocationId() {
      if (requestedDropLocationIdBuilder_ == null) {
        requestedDropLocationId_ = null;
        onChanged();
      } else {
        requestedDropLocationId_ = null;
        requestedDropLocationIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Location requested_drop_location_id = 4;</code>
     */
    public via.sep3.grpcserver.protobuf.notificationservices.Location.Builder getRequestedDropLocationIdBuilder() {
      
      onChanged();
      return getRequestedDropLocationIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.Location requested_drop_location_id = 4;</code>
     */
    public via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder getRequestedDropLocationIdOrBuilder() {
      if (requestedDropLocationIdBuilder_ != null) {
        return requestedDropLocationIdBuilder_.getMessageOrBuilder();
      } else {
        return requestedDropLocationId_ == null ?
            via.sep3.grpcserver.protobuf.notificationservices.Location.getDefaultInstance() : requestedDropLocationId_;
      }
    }
    /**
     * <code>.Location requested_drop_location_id = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.grpcserver.protobuf.notificationservices.Location, via.sep3.grpcserver.protobuf.notificationservices.Location.Builder, via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder> 
        getRequestedDropLocationIdFieldBuilder() {
      if (requestedDropLocationIdBuilder_ == null) {
        requestedDropLocationIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.grpcserver.protobuf.notificationservices.Location, via.sep3.grpcserver.protobuf.notificationservices.Location.Builder, via.sep3.grpcserver.protobuf.notificationservices.LocationOrBuilder>(
                getRequestedDropLocationId(),
                getParentForChildren(),
                isClean());
        requestedDropLocationId_ = null;
      }
      return requestedDropLocationIdBuilder_;
    }

    private double seatPrice_ ;
    /**
     * <code>double seat_price = 5;</code>
     * @return The seatPrice.
     */
    @java.lang.Override
    public double getSeatPrice() {
      return seatPrice_;
    }
    /**
     * <code>double seat_price = 5;</code>
     * @param value The seatPrice to set.
     * @return This builder for chaining.
     */
    public Builder setSeatPrice(double value) {
      
      seatPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double seat_price = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeatPrice() {
      
      seatPrice_ = 0D;
      onChanged();
      return this;
    }

    private int seatCount_ ;
    /**
     * <code>int32 seat_count = 6;</code>
     * @return The seatCount.
     */
    @java.lang.Override
    public int getSeatCount() {
      return seatCount_;
    }
    /**
     * <code>int32 seat_count = 6;</code>
     * @param value The seatCount to set.
     * @return This builder for chaining.
     */
    public Builder setSeatCount(int value) {
      
      seatCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 seat_count = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeatCount() {
      
      seatCount_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <code>string msg = 7;</code>
     * @return The msg.
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg = 7;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg = 7;</code>
     * @param value The msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 7;</code>
     * @param value The bytes for msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 8;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 8;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int tripId_ ;
    /**
     * <code>int32 trip_id = 9;</code>
     * @return The tripId.
     */
    @java.lang.Override
    public int getTripId() {
      return tripId_;
    }
    /**
     * <code>int32 trip_id = 9;</code>
     * @param value The tripId to set.
     * @return This builder for chaining.
     */
    public Builder setTripId(int value) {
      
      tripId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 trip_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTripId() {
      
      tripId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReturnedNotification)
  }

  // @@protoc_insertion_point(class_scope:ReturnedNotification)
  private static final via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification();
  }

  public static via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReturnedNotification>
      PARSER = new com.google.protobuf.AbstractParser<ReturnedNotification>() {
    @java.lang.Override
    public ReturnedNotification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReturnedNotification(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReturnedNotification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReturnedNotification> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.grpcserver.protobuf.notificationservices.ReturnedNotification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

