// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package via.sep3.grpcserver.protobuf.userservices;

public interface GetUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
