// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package via.sep3.grpcserver.protobuf.userservices;

public interface LoginUserMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginUserMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
