// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package via.sep3.grpcserver.protobuf.userservices;

public interface RequestUserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestUserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string first_name = 3;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 3;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 4;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 4;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string phone = 5;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 5;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string address = 6;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 6;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>optional string drive_license = 7;</code>
   * @return Whether the driveLicense field is set.
   */
  boolean hasDriveLicense();
  /**
   * <code>optional string drive_license = 7;</code>
   * @return The driveLicense.
   */
  java.lang.String getDriveLicense();
  /**
   * <code>optional string drive_license = 7;</code>
   * @return The bytes for driveLicense.
   */
  com.google.protobuf.ByteString
      getDriveLicenseBytes();
}
